version: "3.7"

services:
  userinterface_service:
    image: userinterface:latest
    container_name: userinterface
    hostname: userinterface
    environment:
      SPRING_DATASOURCE_URL: ${url_docker_food}
      SPRING_DATASOURCE_USERNAME: ${user}
      SPRING_DATASOURCE_PASSWORD: ${password}
    ports:
      - "8080:8080"
    networks:
      - food_shop_network
  userregistration_service:
    image: userregistration:latest
    container_name: userregistration
    environment:
      SPRING_DATASOURCE_URL: ${url_docker_customers}
      SPRING_DATASOURCE_USERNAME: ${user}
      SPRING_DATASOURCE_PASSWORD: ${password}
    ports:
      - "8081:8081"
    networks:
      - food_shop_network
  userauthentication_service:
    image: userauthentication:latest
    container_name: userauthentication
    environment:
      SPRING_DATASOURCE_URL: ${url_docker_customers}
      SPRING_DATASOURCE_USERNAME: ${user}
      SPRING_DATASOURCE_PASSWORD: ${password}
    ports:
      - "8082:8082"
    networks:
      - food_shop_network
  foodorderproducer_service:
    image: foodorderproducer:latest
    container_name: foodorderproducer
    hostname: foodorderproducer
    ports:
      - "8084:8084"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      APP_KAFKA_TOPIC_NAME: "food.order.topic"
    networks:
      - food_shop_network
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    networks:
      - food_shop_network
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:29092
    depends_on:
      - kafka
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    networks:
      - food_shop_network
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_ENABLE_AUTH: "no"
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "zkServer.sh", "status" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    restart: unless-stopped
    networks:
      - food_shop_network
    ports:
      - "9092:9092"    # External client connections
      - "29092:29092"   # Internal Docker network connections
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_NUM_PARTITIONS: "3"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 6
networks:
  food_shop_network:
    name: food_shop_network
    driver: bridge